// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCSbRrugK987884cBtYrtZwZKO_GRa58',
    appId: '1:1051553601344:web:70df4970af8ac53c3c0ca5',
    messagingSenderId: '1051553601344',
    projectId: 'farmmobimarket',
    authDomain: 'farmmobimarket.firebaseapp.com',
    storageBucket: 'farmmobimarket.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy_QVL8zSXJzqvFiH3aa5sWG_D_GnWQQk',
    appId: '1:1051553601344:android:f192da7b5137deb23c0ca5',
    messagingSenderId: '1051553601344',
    projectId: 'farmmobimarket',
    storageBucket: 'farmmobimarket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZcSU2qqg9NJi1nujJXnqVALd73yPL0Uw',
    appId: '1:1051553601344:ios:5a6e4556abc4f63f3c0ca5',
    messagingSenderId: '1051553601344',
    projectId: 'farmmobimarket',
    storageBucket: 'farmmobimarket.firebasestorage.app',
    iosBundleId: 'com.farmmobi.farmer360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZcSU2qqg9NJi1nujJXnqVALd73yPL0Uw',
    appId: '1:1051553601344:ios:5a6e4556abc4f63f3c0ca5',
    messagingSenderId: '1051553601344',
    projectId: 'farmmobimarket',
    storageBucket: 'farmmobimarket.firebasestorage.app',
    iosBundleId: 'com.farmmobi.farmer360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATCSbRrugK987884cBtYrtZwZKO_GRa58',
    appId: '1:1051553601344:web:1b8429b3732fb5f83c0ca5',
    messagingSenderId: '1051553601344',
    projectId: 'farmmobimarket',
    authDomain: 'farmmobimarket.firebaseapp.com',
    storageBucket: 'farmmobimarket.firebasestorage.app',
  );

}