// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJBsZylY9nH_f_PbCqGmw-1iSRM0oroVY',
    appId: '1:732261515411:web:721f546f616ad070e74d66',
    messagingSenderId: '732261515411',
    projectId: 'procurement-bd262',
    authDomain: 'procurement-bd262.firebaseapp.com',
    databaseURL: 'https://procurement-bd262-default-rtdb.firebaseio.com',
    storageBucket: 'procurement-bd262.firebasestorage.app',
    measurementId: 'G-0PTFVED7B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtMUk6WqASqu08YlH5E82iHbHcBcGpl4',
    appId: '1:732261515411:android:e137dfe1e764ac45e74d66',
    messagingSenderId: '732261515411',
    projectId: 'procurement-bd262',
    databaseURL: 'https://procurement-bd262-default-rtdb.firebaseio.com',
    storageBucket: 'procurement-bd262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5yDzoX8_WL1DiF29zRD-T88D3ZBnKa54',
    appId: '1:732261515411:ios:92c0d2c8c81a9469e74d66',
    messagingSenderId: '732261515411',
    projectId: 'procurement-bd262',
    databaseURL: 'https://procurement-bd262-default-rtdb.firebaseio.com',
    storageBucket: 'procurement-bd262.firebasestorage.app',
    iosBundleId: 'com.farmmobi.farmer360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5yDzoX8_WL1DiF29zRD-T88D3ZBnKa54',
    appId: '1:732261515411:ios:92c0d2c8c81a9469e74d66',
    messagingSenderId: '732261515411',
    projectId: 'procurement-bd262',
    databaseURL: 'https://procurement-bd262-default-rtdb.firebaseio.com',
    storageBucket: 'procurement-bd262.firebasestorage.app',
    iosBundleId: 'com.farmmobi.farmer360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJBsZylY9nH_f_PbCqGmw-1iSRM0oroVY',
    appId: '1:732261515411:web:ff19009cd14ff0ade74d66',
    messagingSenderId: '732261515411',
    projectId: 'procurement-bd262',
    authDomain: 'procurement-bd262.firebaseapp.com',
    databaseURL: 'https://procurement-bd262-default-rtdb.firebaseio.com',
    storageBucket: 'procurement-bd262.firebasestorage.app',
    measurementId: 'G-7NYPRP2DYV',
  );
}
